apiVersion: v1
kind: Secret
metadata:
  name: hrms-secrets
  namespace: hrms
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hr_management_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
  SPRING_DATASOURCE_USERNAME: hr_user
  SPRING_DATASOURCE_PASSWORD: change-me
  AI_GEMINI_API_KEY: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
